name: Terraform Azure Infrastructure

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  terraform-plan:

    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 4. Terraform Initialize
      - name: Terraform Init
        run: terraform init

      # 5. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan